@startuml Adapter Pattern Class Diagram

skinparam classAttributeIconSize 0

class IdentityProviderLoginController {
    +ResponseEntity<String> login(String username, String password)
}

class SmsVerifyLoginController {
    +ResponseEntity<String> login(String verificationCode)
}

abstract class LoginService {
    +String login()
    #abstract String getUsername()
}

class IdentityProviderLoginService {
    -String username
    -String password
    +IdentityProviderLoginService(String username, String password)
    +String getUsername()
    +boolean authenticate()
}

class IdentityProviderLoginServiceAdapter {
    -IdentityProviderLoginService identityProviderLoginService
    +IdentityProviderLoginServiceAdapter(IdentityProviderLoginService identityProviderLoginService)
    +String getUsername()
}

class SmsVerifyLoginService {
    -String verificationCode
    +SmsVerifyLoginService(String verificationCode)
    +String getUsername()
    +boolean authenticate()
}

class SmsVerifyLoginServiceAdapter {
    -SmsVerifyLoginService smsVerifyLoginService
    +SmsVerifyLoginServiceAdapter(SmsVerifyLoginService smsVerifyLoginService)
    +String getUsername()
}

IdentityProviderLoginController --> IdentityProviderLoginServiceAdapter
IdentityProviderLoginServiceAdapter --|> LoginService
IdentityProviderLoginServiceAdapter --> IdentityProviderLoginService

SmsVerifyLoginController --> SmsVerifyLoginServiceAdapter
SmsVerifyLoginServiceAdapter --|> LoginService
SmsVerifyLoginServiceAdapter --> SmsVerifyLoginService

@enduml
