@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title C4 Container Diagram - Ansie

Person(Student, "Student", "A student who uses the system to take exams")
Person(Teacher, "Teacher", "A teacher who uses the system to create and grade exams")

System_Boundary(Ansie, "Ansie") {
    Container(Web_app, "Web app", "Handles the users requests")
    Container(Backend, "Backend", "Handles all the logic inside Ansie")
    ContainerDb(SQLServer, "SQL Server", "Contains all data used by Ansie")
}

System_Ext(Osiris, "Osiris", "Contains registered students for exams")
System_Ext(SchoolYear, "SchoolYear", "Secures Ansie so it can only be used in a safe browser")

Web_app --> Backend : "Sends Request to endpoints (HTTP/JSON)"
Backend --> Osiris : "Publishing grades(?)"
Web_app --> SchoolYear : "Save browsing(?)"
Backend --> SQLServer : "Requests data from database (IP/TCP/SQL)"
Student --> Web_app
Teacher --> Web_app

@enduml
