@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_WITH_LEGEND()

title Component diagram voor Frontend van TripTop

Person(Reiziger, "Reiziger", "Een reiziger die het systeem gebruikt om een vakantie te boeken")
Person(Reisagent, "Reisagent", "Een reisagent die het systeem gebruikt om een reiziger te helpen")

Container_Boundary(api, "Frontend van TravelExpensePro") {
    Component(App, "App", "React Component", "Componenten worden ingeladen vannuit de App")
    Component(InlogScherm, "Inlog Scherm", "React Component", "Scherm om in te loggen")
    Component(InlogFormulier, "Inlog Formulier", "React Component", "Formulier om in te loggen")
    Component(Kaart, "Kaart", "React Component", "Een map met vliegvelden hotels")
    Component(HotelOverzicht, "Hotel Overzicht", "React Component", "Overzicht van hotels")
    Component(HotelLijst, "Hotellijst", "React Component", "Lijst van hotels")
    Component(Hotel, "Hotel", "React Component", "Component haalt hotels op")
    Component(VluchtOverzicht, "Vlucht Overzicht", "React Component", "Overzicht van vluchten")
    Component(VluchtLijst, "Vlucht Lijst", "React Component", "Lijst van vluchten")
    Component(Vlucht, "Vlucht", "React Component", "Component haalt vluchten op")
    Component(Vliegveld, "Vliegveld", "React Component", "Component haalt vliegvelden op")

    Rel(Reiziger, App, "Gebruikt", "JSON/HTTPS")
    Rel(Reisagent, App, "Gebruikt", "JSON/HTTPS")
    Rel(App, InlogScherm, "navigeert naar")
    Rel(App, Kaart, "navigeert naar")
    Rel(App, HotelOverzicht, "navigeert naar")
    Rel(InlogScherm, InlogFormulier, "Laadt in")
    Rel(HotelOverzicht, HotelLijst, "Laadt in")
    Rel(HotelLijst, Hotel, "Laadt in")
    Rel(Kaart, Hotel, "Geeft weer")
    Rel(Kaart, Vliegveld, "Geeft weer")
    Rel(App, VluchtOverzicht, "navigeert naar")
    Rel(VluchtOverzicht, VluchtLijst, "Laadt in")
    Rel(VluchtLijst, Vlucht, "Laadt in")
    Rel(VluchtLijst, Vliegveld, "Laadt in")
}

Container(backend, "Backend", "Spring Boot, Java", "Backend van de applicatie")
System_Ext(GoogleMapsAPI, "Google Maps API", "Haalt kaartinformatie op", "HTTP/JSON")
Rel(InlogScherm, backend, "Controleert of gegevens kloppen", "HTTP/JSON")
Rel(Hotel, backend, "Haalt accomodaties op", "HTTP/JSON")
Rel(Vlucht, backend, "Haalt vluchten op", "HTTP/JSON")
Rel(Vliegveld, backend, "Haalt vliegvelden op", "HTTP/JSON")
Rel(Kaart, GoogleMapsAPI, "Haalt kaartgegevens op", "HTTP/JSON")
SHOW_LEGEND()
@enduml