@startuml
!include <C4/C4_Container>

title C4 Context Diagram - TripTop

Person(Reiziger, "Reiziger", "Gebruikt de applicatie om reizen te plannen")
Person(ReisAgent, "ReisAgent", "Biedt hulp bij het plannen van reizen")

System(TripTop, "TripTop Applicatie", "Applicatie voor het plannen van reizen")

System_Ext(IdentityProvider, "Identity Provider", "Verifieert gebruikersidentiteit")
System_Ext(Google_maps_api, "Google maps API", "API voor het opvragen van kaarten")
System_Ext(Booking, "Booking.com", "API voor het boeken van accomodaties")
System_Ext(AirScraper, "AirScraper", "API voor vluchtinformatie")

Reiziger --> TripTop : "Plant reizen"
ReisAgent --> TripTop : "Helpt Reizigers met reisplanning"

TripTop --> IdentityProvider : "Authentiseert en autoriseert gebruikers"
TripTop --> Google_maps_api : "Haalt informatie op over kaarten"
TripTop --> Booking : "Haalt informatie op over accomodaties"
TripTop --> AirScraper : "Haalt informatie op over vluchten"

SHOW_LEGEND(true)
@enduml
