@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title C4 Dynamic Container Diagram Inloggen - TripTop

Person(Reiziger, "Reiziger", "Een reiziger die het systeem gebruikt om een vakantie te boeken")

Container_Boundary(ContainerBoundary, "Container Boundary") {
    Container(Frontend, "Frontend", "React/JavaScript", "Frontend interface voor TripTop")
    Container(Backend, "Backend", "Java", "Handelt applicatie logica en API requests af")
}
Container(IdentityProvider, "IdentityProvider", "External System", "Handelt authenticatie en authorizatie af")

Rel(Reiziger, Frontend, "1: Vult inloggevens in", $techn="HTTP", $tags="", $link="")
Rel(Frontend, Backend, "2: Verstuurt inloggevens", $techn="HTTP", $tags="", $link="")
Rel(Backend, IdentityProvider, "3: Valideert inloggegevens", $techn="HTTP", $tags="", $link="")
Rel(IdentityProvider, Backend, "4: Retourneert authenticatietoken", $techn="HTTP", $tags="", $link="")
Rel(Backend, Frontend, "5: Retourneert gebruikersessiegegevens", $techn="HTTP", $tags="", $link="")
Rel(Frontend, Reiziger, "6: Gebruiker is ingelogd en wordt doorgestuurd naar het dashboard", $techn="HTTP", $tags="", $link="")

SHOW_LEGEND(true)
@enduml
