@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


Person(Bezoeker, "Bezoeker", "Een bezoeker die het systeem gebruikt om zijn uitgaven te beheren")
Container(Frontend, "Frontend", "Een frotend die de inputs van de gebruiker verwerkt en door stuurt")

Container_Boundary(ContainerBoundary, "Backend") {

Component(LoginController, "LoginController", "test")
Component(LoginService, "LoginService", "test")
Component(LoginRepository, "LoginRepository", "test")

Component(ExpenseEntryController, "ExpenseEntryController", "test")
Component(ExpenseEntryService, "ExpenseEntryService", "test")
Component(ExpenseEntryRepository, "ExpenseEntryRepository", "test")

Component(ExpenseOverviewController, "ExpenseOverviewController", "test")
Component(ExpenseOverviewService, "ExpenseOverviewService", "test")
Component(ExpenseOverviewRepository, "ExpenseOverviewRepository", "test")
                                                  }

ContainerDb(Externe_Database," ExterneDatabase","test")

Bezoeker --> Frontend

Frontend --> LoginController
Frontend --> ExpenseEntryController
Frontend --> ExpenseOverviewController

LoginController --> LoginService
LoginService --> LoginRepository
LoginRepository --> Externe_Database

ExpenseEntryController --> ExpenseEntryService
ExpenseEntryService --> ExpenseEntryRepository
ExpenseEntryRepository --> Externe_Database

ExpenseOverviewController --> ExpenseOverviewService
ExpenseOverviewService --> ExpenseOverviewRepository
ExpenseOverviewRepository --> Externe_Database

@enduml