@startuml

state Gepland {
}

state Geregeld {
}

state Betaald {
}

state Uitgevoerd {
}

state Niet_Uitvoerbaar {
}

[*] --> Gepland
Gepland --> Geregeld : "gebruiker boekt een bouwblok"
Geregeld --> Betaald : "gebruiker betaalt voor een bouwblok"
Betaald --> Uitgevoerd : "gebruiker voert zijn boeking om=p het bouwblok uit"
Uitgevoerd --> [*]

Gepland --> Niet_Uitvoerbaar : "als de gebruiker zijn booking wilt annuleren"
Geregeld --> Niet_Uitvoerbaar: "als de gebruiker zijn booking wilt annuleren"
Betaald --> Niet_Uitvoerbaar: "als de gebruiker zijn booking wilt annuleren"
Niet_Uitvoerbaar --> [*]


@enduml