@startuml

[*] --> WorkingState
WorkingState -> RetryState : "Exception"
RetryState -> FallbackState : "counter >= MAX_RETRIES"
FallbackState -> WorkingState : "response.getStatusCode().is2xxSuccessful()""
FallbackState --> [*] : "Exception"

@enduml
