@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title C4 Dynamic Container Diagram Airscraper API - TripTop
left to right direction

Person(Reiziger, "Reiziger", "Een reiziger die het systeem gebruikt om vluchten te zoeken")
Container(WebApp, "WebApplication", "React/JavaScript", "Frontend interface voor TripTop")

Container_Boundary(ContainerBoundary, "Container Boundary") {
    Component(VluchtController, "VluchtController", "Java/SpringBoot", "Behandelt de inputs van de frontend voor vluchten")
    Component(VluchtActionHandler, "VluchtActionHandler", "Java/SpringBoot", "Behandelt of de gebruiker de acties uit mag voeren op zijn vlucht")
    Component(InlogActionHandler, "InlogActionHandler", "Java/SpringBoot", "Behandelt de gegevens van de gebruiker en controleert de inlog")
    Component(VluchtService, "VluchtService", "Java/SpringBoot", "Behandelt request sturen naar de API en de data op de goede manier doorgeven aan de rest van de applicatie")
}

System_Ext(Airscraper, "Airscraper", "Haalt alle vluchtgegevens op voor het boeken van een vlucht")

Rel(Reiziger, WebApp, "1: Selecteert vlucht om te boeken", $techn="HTTP", $tags="", $link="")
Rel(WebApp, VluchtController, "2: Verstuurt vlucht details", $techn="HTTP", $tags="", $link="")
Rel(VluchtController, VluchtActionHandler, "3: Roept actie aan om een vlucht te boeken", $techn="", $tags="", $link="")
Rel(VluchtActionHandler, InlogActionHandler, "4: Controleert of de gebruiker is ingelogd", $techn="", $tags="", $link="")
Rel(InlogActionHandler, VluchtActionHandler, "5: Verstuurd gebruiker gegevens terug", $techn="", $tags="", $link="")
Rel(VluchtActionHandler, VluchtService, "6: Roept actie aan om een vlucht te boeken", $techn="", $tags="", $link="")
Rel(VluchtService, Airscraper, "7: Verstuurt API request om een vlucht te boeken", $techn="HTTP", $tags="", $link="")
Rel(Airscraper, VluchtService, "8: Verstuurt API response", $techn="HTTP", $tags="", $link="")
Rel(VluchtService, VluchtActionHandler, "9: Stuurt resultaat door om staat aan te passen", $techn="", $tags="", $link="")
Rel(VluchtActionHandler, VluchtController, "10: Stuurt resultaat door", $techn="", $tags="", $link="")
Rel(VluchtController, WebApp, "11: Stuurt resultaat door", $techn="HTTP", $tags="", $link="")
Rel(WebApp, Reiziger, "12: Toont resultaat van de boeking", $techn="HTML", $tags="", $link="")

SHOW_LEGEND(true)
@enduml
