@startuml

title Sequence Diagram for getFlights

actor Gebruiker
participant "VluchtController" as VC
participant "VluchtService" as VS
participant "ApiGateway" as AG
participant "ApiState" as State

Gebruiker -> VC: GET /getFlights
VC -> VS: getFlights()
VS -> AG: getFlights()
AG -> State: execute(this, url)
State -> AG: fetchResponse(url)
AG -> VS: ResponseEntity<String>
VS -> VC: ResponseEntity<String>
VC -> Gebruiker: ResponseEntity<String>

@enduml